name: Compile Clang.c with gcc Workflow

on:
  push:
    branches:
      - main

jobs:
  compile_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Compile clang.c
        run: |
          gcc clang.c -o hello

      - name: Test the executable
        run: |
         ./hello
